export const CATEGORIES_DATA = [
  {
    title: 'Grand Theft Auto V',
    slug: 'grand-theft-auto-v',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/grand-theft-auto-v.webp',
  },
  {
    title: 'Monster Hunter Wilds',
    slug: 'monster-hunter-wilds',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/monster-hunter-wilds.webp',
  },
  {
    title: 'Avowed',
    slug: 'avowed',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/avowed.webp',
  },
  {
    title: 'Ghost of Yōtei',
    slug: 'ghost-of-yotei',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/ghost-of-yotei.webp',
  },
  {
    title: 'Call of Duty: Black Ops 6',
    slug: 'call-of-duty-black-ops-6',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/call-of-duty-black-ops-6.webp',
  },
  {
    title: 'Elden Ring: Shadows of the Erdtree',
    slug: 'elden-ring-shadows-of-the-erdtree',
    description:
      "Immerse yourself in the sprawling open world of Vice City in 'Grand Theft Auto VI'. Engage in high-speed chases, intricate heists, and explore a city teeming with life and opportunities. With its rich narrative and expansive environment, players can experience both the main storyline and a plethora of side activities, ensuring endless entertainment in this highly anticipated installment.",
    thumbnailUrl: '/categories/elden-ring-shadows-of-the-erdtree.webp',
  },
  {
    title: 'FIFA 25',
    slug: 'fifa-25',
    description:
      "Step onto the pitch with 'FIFA 25', the latest installment in the renowned football simulation series. Experience realistic gameplay, updated rosters, and immersive game modes that bring the world's most popular sport to life. Whether you're managing a club or competing online, 'FIFA 25' offers unparalleled football action.",
    thumbnailUrl: '/categories/fifa-25.webp',
  },
  {
    title: 'Minecraft',
    slug: 'minecraft',
    description:
      "Unleash your creativity in 'Minecraft', the sandbox game that continues to captivate players of all ages. Build intricate structures, explore vast worlds, and embark on adventures in a game where the only limit is your imagination. With continuous updates and a vibrant community, 'Minecraft' remains a cornerstone of gaming.",
    thumbnailUrl: '/categories/minecraft.webp',
  },
  {
    title: "Marvel's Spider-Man 2",
    slug: 'marvels-spider-man-2',
    description:
      "Swing through the streets of New York City in 'Marvel's Spider-Man 2'. Play as Peter Parker and Miles Morales, facing new villains and challenges in this action-packed sequel. With its compelling story and dynamic gameplay, players can experience the thrill of being Spider-Man like never before.",
    thumbnailUrl: '/categories/marvels-spider-man-2.webp',
  },
  {
    title: 'Hogwarts Legacy',
    slug: 'hogwarts-legacy',
    description:
      "Attend Hogwarts School of Witchcraft and Wizardry in 'Hogwarts Legacy'. Create your own wizarding story, learn spells, brew potions, and explore the magical world set in the 1800s. This immersive RPG allows fans to experience the wizarding world in a new era, filled with magic and mystery.",
    thumbnailUrl: '/categories/hogwarts-legacy.webp',
  },
  {
    title: 'Art & Design',
    slug: 'art-and-design',
    description:
      'Discover live sessions where artists showcase their creative processes, from digital illustrations to traditional painting techniques. Engage with creators as they bring their visions to life, offering inspiration and insights into the world of art and design.',
    thumbnailUrl: '/categories/art-and-design.webp',
  },
  {
    title: 'Cooking & Food',
    slug: 'cooking-and-food',
    description:
      'Join culinary enthusiasts and professional chefs as they prepare delectable dishes from around the globe. Learn new recipes, cooking techniques, and immerse yourself in the rich world of gastronomy through interactive and engaging live streams.',
    thumbnailUrl: '/categories/cooking-and-food.webp',
  },
];

export const STREAM_TITLES = {
  'grand-theft-auto-v': [
    'Chaos in Los Santos – Can We Survive?',
    'GTA V Roleplay: The Ultimate Heist',
    'Fast Cars, High Stakes – Street Racing Night',
    'Becoming a GTA Crime Lord in One Stream',
    'Los Santos Cops & Robbers – Who Wins?',
    'GTA Online Shenanigans – Anything Goes!',
    'Epic Stunt Challenge – Insane Jumps Only!',
    'GTA V Mod Madness – Breaking the Game',
    '24 Hours in GTA V – Can We Make Millions?',
    'The Ultimate GTA V Story Mode Speedrun',
  ],
  'monster-hunter-wilds': [
    'Hunting the Biggest Beasts in Wilds!',
    'New Monster, New Strategy – Can We Win?',
    'Solo vs. Multiplayer – Which Hunt is Harder?',
    'Crafting the Ultimate Armor Set LIVE!',
    'Monster Hunter Wilds – First Time Reactions!',
    'Fastest Hunts Only – Speedrun Challenge!',
    'Fighting Every Boss in One Stream!',
    'Weapon Mastery – Trying Every Build!',
    'Monster Hunter Wilds: Hardcore Mode ON!',
    'Hunting with Viewers – Let’s Team Up!',
  ],
  avowed: [
    'Deep Dive into Avowed – Story & Lore!',
    'Best Spells & Builds for Avowed’s Combat!',
    'Avowed’s Open World – What Can We Discover?',
    'Making the Toughest Choices in Avowed',
    'Avowed Gameplay – Is It Worth the Hype?',
    'Speedrunning Avowed – Any % Attempt!',
    'Ultimate Magic-Only Run – No Weapons Allowed!',
    'Hidden Secrets & Easter Eggs in Avowed',
    'Building the Strongest Character – RPG Deep Dive',
    'Hardest Difficulty Challenge – Can We Beat It?',
  ],
  'ghost-of-yotei': [
    'Ghost of Yōtei First Impressions – Samurai or Spirit?',
    'Mastering the Blade – Combat Breakdown!',
    'Exploring Yōtei’s Beautiful Open World',
    'Ghost Mode Only – Can We Stealth Everything?',
    'Boss Rush! Defeating Every Enemy in One Stream',
    'Ghost of Yōtei Story Reactions – Live Playthrough!',
    'Hardest Difficulty – No HUD, No Mercy!',
    'Unraveling Yōtei’s Deepest Mysteries',
    'Ghost vs. Human Combat – Which is More Powerful?',
    'Speedrunning Ghost of Yōtei – New Record?',
  ],
  'call-of-duty-black-ops-6': [
    'Black Ops 6 Multiplayer – First Matches LIVE!',
    'Best Loadouts for DOMINATING in BO6',
    'Zombies Mode Madness – How Long Can We Survive?',
    'Black Ops 6 Campaign – Realistic Mode Only!',
    '1v1 Me Bro! Sniper Duels in BO6',
    'No Scope, No Problem – Trickshot Challenge!',
    'Becoming a PRO in BO6 Ranked Mode',
    'All Killstreaks Unlocked – Maximum Mayhem!',
    'Trolling in BO6 – Funniest Moments!',
    'Black Ops 6 Warzone – Dropping HOT!',
  ],
  'elden-ring-shadows-of-the-erdtree': [
    'New DLC, New Challenges – Exploring the Erdtree!',
    'Hardest Bosses in Shadows of the Erdtree!',
    'No Death Run Attempt – Can We Survive?',
    'Ultimate Build Guide for the DLC',
    'Uncovering Every Secret in the New Expansion!',
    'Shadows of the Erdtree – Blind Playthrough LIVE!',
    'PvP Duels – Testing the New DLC Weapons!',
    'Shadows of the Erdtree – Boss Ranking LIVE!',
    'Speedrun Challenge – Can We Beat the DLC Fast?',
    'Lore Deep Dive – What Does It All Mean?',
  ],
  'fifa-25': [
    'FIFA 25 Career Mode – Building the Ultimate Team!',
    'FUT Pack Opening – Can We Get a Legend?',
    'Road to Glory – No Pay-to-Win Challenge!',
    'FIFA 25 Skill Moves Masterclass!',
    'Becoming the Best Manager in FIFA 25',
    'Ultimate Rivals Matchup – Who’s the GOAT?',
    'FIFA 25 Online – Can We Go Undefeated?',
    'Penalty Shootout Challenge – No Room for Errors!',
    'Winning the World Cup with a 1-Star Team!',
    'Best Goals Compilation – FIFA 25 Edition!',
  ],
  minecraft: [
    'Hardcore Survival – No Second Chances!',
    'Building the Ultimate Mega Base LIVE!',
    'Speedrunning Minecraft – New PB Attempt!',
    'Minecraft Mods That Change Everything!',
    'Surviving 100 Days in Hardcore Mode!',
    'Trolling My Friends in Minecraft – Hilarious!',
    'Beating Minecraft Without Mining!',
    'Minecraft Manhunt – Can I Escape?',
    'Exploring the Deep Dark – Warden Encounter!',
    'Building a Theme Park in Minecraft – Creative Mode!',
  ],
  'marvels-spider-man-2': [
    'Swinging Through NYC – Spider-Man 2 LIVE!',
    'Peter vs. Miles – Who’s the Best Spider-Man?',
    "Marvel's Spider-Man 2 – Insane Combat Combos!",
    'Finding Every Secret Suit in the Game!',
    'Web-Slinging Parkour Challenge – No Ground Touch!',
    'Ultimate Difficulty – No Damage Run!',
    'Spider-Man 2 Story Playthrough – Full Experience!',
    'Venom vs. Spider-Man – Epic Battles LIVE!',
    'Exploring New York’s Easter Eggs!',
    'Fastest Swing Speed – Can We Break Records?',
  ],
  'hogwarts-legacy': [
    'Hogwarts Legacy – Ultimate Wizard Playthrough!',
    'Best Spells & Builds – Hogwarts Battle Guide!',
    'Dark Arts Only – Becoming the Ultimate Villain!',
    'Hogwarts Legacy Secrets – Every Easter Egg!',
    'Sorting Hat Challenge – No Restart Allowed!',
    'No Wand Run – Can We Survive Hogwarts?',
    'Hogwarts Legacy Hardcore Mode – No Healing!',
    'Creating the Best Wizard Character LIVE!',
    'Flying Through Hogwarts – Broomstick Challenges!',
    'Exploring Forbidden Locations – What’s Hidden?',
  ],
  'art-and-design': [
    'Live Digital Painting – Creating a Fantasy Scene!',
    'Speedpainting Challenge – 10-Minute Art!',
    'Trying New Art Styles – What Works Best?',
    'Pixel Art Animation – Creating a Game Sprite!',
    'Sketching Live – Taking Viewer Suggestions!',
    '3D Sculpting Challenge – Character Design!',
    'Watercolor vs. Digital – Which Looks Better?',
    'Art Critique & Improvement – Submit Your Work!',
    'Live Logo Design – From Idea to Final Product!',
    'Typography Art – Creating Letter-Based Designs!',
  ],
  'cooking-and-food': [
    'Cooking a 3-Course Meal – Can I Pull It Off?',
    'Live Baking Challenge – No Recipe Allowed!',
    'Trying Viral Food Trends – Success or Fail?',
    'Making the Perfect Pizza from Scratch!',
    'Street Food Recipes – Bringing the Flavor Home!',
    'Cooking with Limited Ingredients – What’s Possible?',
    'Live Taste Test – Weird Food Combos!',
    'How to Cook Like a Pro – Live Kitchen Tips!',
    'The Ultimate Burger Cook-Off!',
    'Viewers Pick the Ingredients – Chaos in the Kitchen!',
  ],
};

export const USERNAMES = [
  'talasius',
  'PixelPhantom',
  'GameGuru88',
  'NeonNexus',
  'EpicByte',
  'StealthGamer',
  'TurboTornado',
  'GlitchVortex',
  'FrostByte64',
  'DarkKnightXP',
  'QuantumQuest',
  'LevelUpLynx',
  'CyberChampion',
  'EliteShadow',
  'VenomVortex',
  'PixelSamurai',
  'ArcadeAce',
  'InfernoGamer',
  'CosmicCrusader',
  'ZeroLagWarrior',
  'LegendSlayer99',
  'SpeedrunSpecter',
  'WarpedReality',
  'GhostlyGamer',
  'XPGrindMaster',
  'NexusReaper',
  'NightmareNinja',
  'VictoryViper',
  'SkylineGamer',
  'DragonByte',
  'StealthSniper',
  'BlitzBattler',
  'RoguePixel',
  'TacticalTitan',
  'VoltageViper',
  'OmegaStriker',
  'DigitalDominator',
  'NeonSpecter',
  'StormChaserX',
  'PhantomByte',
  'FirestormFox',
  'AetherGamer',
  'RespawnRanger',
  'WraithWanderer',
  'OblivionPlayer',
  'TurboBlaze',
  'RetroRocket',
  'LunarLegend',
  'CrimsonGhost',
  'ShadowProwler',
  'PixelNomad',
  'XtremeWarrior',
  'HavocHacker',
  'ToxicTornado',
  'QuantumSpecter',
  'BinaryBrawler',
  'NovaSniper',
  'WarpDriveGamer',
  'FeralPhantom',
  'GlitchHunter',
  'CodeBreakerX',
  'MysticByte',
  'SilentStorm',
  'PowerUpPhantom',
  'DarkMatterXP',
  'CyberShogun',
  'HorizonHacker',
  'ApexPredatorX',
  'VenomousVortex',
  'FrostFangGamer',
  'ElectricKnight',
  'TurboThrasher',
  'WarpSpeedWolf',
  'SkyboundSamurai',
  'PhantomStriker',
  'FireballFury',
  'NeonRogue',
  'OmegaByte',
  'HyperNovaX',
  'PixelPredator',
  'CyberSentinel',
  'InfinityGamer',
  'GhostGlider',
  'StormSurgeX',
  'CelestialByte',
  'EpicEndgame',
  'CodeNinja88',
  'PowerGlitch',
  'NightHawkXP',
  'ShadowFusion',
  'DragonSlayerX',
  'RetroRampage',
  'SpeedsterGamer',
  'RogueFirestorm',
  'CyberWarden',
  'DigitalShadow',
  'HyperStealth',
  'VictoryRider',
  'PhoenixByte',
  'TacticalPhantom',
  'NeonOverlord',
  'SkyboundStriker',
];
